name: Static Analysis
on: [push, pull_request]
permissions:
  contents: read

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: false
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
